---

name: Go

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: '.'

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-go@v2
        with:
          stable: false
          go-version: '^1'

      - run: go vet

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-go@v2
        with:
          stable: false
          go-version: '^1'

      - run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-go@v2
        with:
          stable: false
          go-version: '^1'

      - run: go test -v ./...

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1'

      - run: |
        out="$(gofmt -d .)"
        if [ -n "$out" ]; then
            echo "$out" && exit 1
        fi

  report:
    runs-on: ubuntu-latest
    steps:
      - uses: creekorful/goreportcard-action@v1.0
